name: Build XPI

on:
  workflow_dispatch:

jobs:
  build-xpi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Upload XPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: zotero-easygpt.xpi
          path: build/*.xpi
